force-app/main/default/objects/Sites__c/Sites__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sites__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Elevation__c.field-meta.xml
<CustomField>
    <fullName>Elevation__c</fullName>
    <label>Elevation (m)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/State_Region__c.field-meta.xml
<CustomField>
    <fullName>State_Region__c</fullName>
    <label>State / Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Federated States of Micronesia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Guam</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Marshall Islands</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Street 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Street 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GeocodeJob.cls
public class GeocodeJob implements Queueable, Database.AllowsCallouts {
    
    private List<Id> siteIds;
    
    private final String GEOBASE   = 'https://maps.googleapis.com/maps/api/geocode/json?';
    private final String ELVBASE   = 'https://maps.googleapis.com/maps/api/elevation/json?';
    private final String KEY      = 'AIzaSyC0p_WScvHdaqKFzO-rBy9066INhsBB-DM';

    public GeocodeJob(List<Id> siteIds) {
        this.siteIds = siteIds;
    }
    
    public void execute(QueueableContext context) {
        List<Sites__c> sitesToUpdate = new List<Sites__c>();
        
        for (Sites__c site : getSites()) {
            Map<String, Double> newLatLng = getLatLng(site.Street_1__c + ' ' + (!String.isBlank(site.Street_2__c) ? site.Street_2__c + ' ' : '') + site.City__c + site.State_Region__c + ' ' + ' ' + site.Country__c);
            
            if (newLatLng == null) {
                continue;
            }
            
            Double newLat = newLatLng.get('lat');
            Double newLng = newLatLng.get('lng');
            
            if (site.Geolocation__Latitude__s == newLat && site.Geolocation__Longitude__s == newLng) {
                continue; // early exit; no change
            }
            
            Sites__c change = new Sites__c(
              Id               = site.Id,
                Geolocation__Latitude__s   = newLat,
                Geolocation__Longitude__s   = newLng
            );
            sitesToUpdate.add(change);
            
            Double newElv = getElevation(String.valueOf(newLat) + ',' + String.valueOf(newLng));
            if (newElv != null) {
                change.Elevation__c = newElv;
            }
        }

        UPDATE sitesToUpdate;
    }
    
    private List<Sites__c> getSites() {
        return [SELECT  Id, 
                    Street_1__c, 
                    Street_2__c, 
                    City__c, 
                    State_Region__c,
                    Country__c, 
                    Geolocation__Latitude__s, 
                    Geolocation__Longitude__s
                FROM    Sites__c 
                WHERE   Id IN :siteIds];
    }
    
    private Map<String, Double> getLatLng(String address) {
        Http h = new Http();
        
        HttpRequest req = new HttpRequest();
              req.setEndpoint(GEOBASE + 'address=' + EncodingUtil.urlEncode(address, 'UTF-8') + '&key=' + KEY);
              req.setMethod('GET');
        
        HttpResponse res = h.send(req);
        
        if (res.getStatusCode() != 200) {
            return null; // early exit - did not get a good response
        }
        
        GResponse g;
        try {
            g = (GResponse)JSON.deserialize(res.getBody(), GResponse.class);
        } catch (Exception ex) {
            System.debug('ISSUE DESERIALIZING GRESPONSE');
            System.debug(ex.getMessage());
        }
        
        if (g == null || g.results.isEmpty()) {
            return null;  // early exit - empty response or issue deserializing
        }
        
        return new Map<String, Double> {
            'lat' => g.results[0].geometry.location.lat,
            'lng' => g.results[0].geometry.location.lng
        };
    }
    
    private Double getElevation(String ip) {
        Http h = new Http();
        
        HttpRequest req = new HttpRequest();
              req.setEndpoint(ELVBASE + 'locations=' + ip + '&key=' + KEY);
              req.setMethod('GET');
        
        HttpResponse res = h.send(req);
        
        EResponse e;
        try {
            e = (EResponse)JSON.deserialize(res.getBody(), EResponse.class);
        } catch (Exception ex) {
            System.debug('ISSUE DESERIALIZING ERESPONSE');
            System.debug(ex.getMessage());
        }
        
        if (e == null || e.results.isEmpty()) {
            return null;  // early exit - empty response or issue deserializing
        }
        
        return e.results[0].elevation;
    }

    private class EResponse {
        private List<EResult> results;
    }
    
    private class EResult {
      private Double elevation;   
    }
    
    private class GResponse {
        private List<GResult> results;
    }
    
    private class GResult {
        private GGeometry geometry;
    }
    
    private class GGeometry {
        private GLocation location;
    }
    
    private class GLocation {
        private Double lat;
        private Double lng;
    }
}