force-app/main/default/objects/Sites__c/Sites__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sites__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/State_Region__c.field-meta.xml
<CustomField>
    <fullName>State_Region__c</fullName>
    <label>State / Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Federated States of Micronesia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Guam</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Marshall Islands</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Street 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Street 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SitesTriggerHandler.cls
public class SitesTriggerHandler {
    
    private static Boolean hasRun = false;
    
    public static void skipProcessing() {
        hasRun = true;
    }
    
    @TestVisible
    private static void reset() {
        hasRun = false;
    }
    
    private static final Set<String> ADDRESS_FIELDS = new Set<String>{
        'Street_1__c',
        'Street_2__c',
        'City__c',
        'State_Region__c',
        'Country__c',
        'Postal_Code__c'
    };
    
    public static void mainEntry(Boolean 			isBefore,
                                 Boolean 			isAfter,
                                 Boolean 			isInsert,
                                 Boolean 			isUpdate,
                                 Boolean 			isDelete,
                                 List<Sites__c> 	newRecs,
                                 Map<Id, Sites__c>  oldMap) 
    {
        if (hasRun) {
            return;
        }
        
        if (isAfter) {
            hasRun = true;
        }
        
        List<String> geocodeIds 		= new List<String>();
        List<String> clearOppys 		= new List<String>();
        Map<String, String> oppyToSite 	= new Map<String, String>();
        
        for (Sites__c n : newRecs) {
         	Sites__c o = oldMap == null ? null : oldMap.get(n.Id);
            if (hasAddressChange(n, o)) {
                geocodeIds.add(n.Id);
            }
            
            if (!String.isBlank(n.Opportunity__c)) {
                String nOpp = n.Opportunity__c;
                if (o == null) {
                    oppyToSite.put(nOpp, n.Id);
                } else {
                    String vOpp = o.Opportunity__c;
                    if (change(nOpp, vOpp)) {
                        oppyToSite.put(nOpp, n.Id);
                        if (!String.isBlank(vOpp)) {
                            clearOppys.add(vOpp);
                        }
                    }
                }
            }
        }
        
        if (!geocodeIds.isEmpty()) {
            System.enqueueJob(new GeocodeJob(geocodeIds));
        }
        
        if (!clearOppys.isEmpty()) {
            SitesManageSiteProducts.clearOppyProducts(clearOppys);
        }
        
        if (!oppyToSite.values().isEmpty()) {
            SitesManageSiteProducts.populateOppyProducts(oppyToSite);
        }
    }
    
    private static Boolean change(String s, String t) {
        return !String.isBlank(s) && s != t;
    }
    
    private static Boolean hasAddressChange(Sites__c n, Sites__c o) {
        for (String f : ADDRESS_FIELDS) {
            String s = (String)n.get(f);
            String t = o == null ? '' : (String)o.get(f);
            if (change(s, t)) {
                return true;
            }
        }
        
        return false;
    }
    
}