force-app/main/default/objects/Sites__c/Sites__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sites__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SitesManageSiteProductsTest.cls
@isTest
private class SitesManageSiteProductsTest {
    
    @isTest
    static void standard() {
        Opportunity opp = new Opportunity(
            Name 		= 'Test class Opportunity',
            StageName 	= 'Prospecting',
            CloseDate 	= Date.today().addDays(30)
        );
        INSERT opp;
        
        Product2 p = new Product2(
        	Name = 'test product'
        );
        INSERT p;
        
       	PricebookEntry pbe = new PricebookEntry(
            Product2Id 		= p.Id,
            Pricebook2Id 	= Test.getStandardPricebookId(),
            UnitPrice		= 0,
            IsActive        = true
        );
        INSERT pbe;
        
        INSERT new OpportunityLineItem(
        	PricebookEntryId 	= pbe.Id,
            Quantity 			= 1,
            UnitPrice 			= 1,
            OpportunityId 		= opp.Id
        );
        
        Sites__c s = new Sites__c(
            Opportunity__c 	= opp.Id
        );
        INSERT s;
        
        Opportunity npp = new Opportunity(
            Name 		= 'Test second Opportunity',
            StageName 	= 'Prospecting',
            CloseDate 	= Date.today().addDays(30)
        );
        INSERT npp;
        
        INSERT new OpportunityLineItem(
        	PricebookEntryId 	= pbe.Id,
            Quantity 			= 1,
            UnitPrice 			= 1,
            OpportunityId 		= npp.Id
        );
        
        SitesTriggerHandler.reset();

        UPDATE new Sites__c(
            Id 				= s.Id,
        	Opportunity__c 	= npp.Id
        );

        for (OpportunityLineItem oli : [SELECT OpportunityId, Site__c FROM OpportunityLineItem]) {
            Assert.areEqual(oli.OpportunityId == npp.Id, oli.Site__c == s.Id, 'Site Line Item Processing incorrect');
        }
    }
}