force-app/main/default/objects/Sites__c/Sites__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sites__c/fields/Active_Sale__c.field-meta.xml
<CustomField>
    <fullName>Active_Sale__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Sale</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/State_Region__c.field-meta.xml
<CustomField>
    <fullName>State_Region__c</fullName>
    <label>State / Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Federated States of Micronesia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Guam</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Marshall Islands</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Street 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestMainspringCiceroQueueable.cls
/**
 * Test class to provide test coverage for the MainspringCiceroQueueable and MainspringCiceroSchedulable
 * Created by DaizyLogik Nov 2023
 */
@isTest
public class TestMainspringCiceroQueueable {
    private static final String jsonError = '{"response": { "errors":[ "No geocoding results found for address"],"messages": [], "results": {"candidates": []}}}';

    @istest
    private static void testMainspringCiceroQueueable() {
        //create Site
       Opportunity opp = new Opportunity(Name ='Test', StageName = 'Initial Assessment', CloseDate=date.today()); 
       insert opp;
       Sites__c site = new Sites__c(Opportunity__c=opp.Id, Name='Test Site', Street_1__c='615 7th Ave', Active_Sale__c = true,
                                       City__c='Santa Cruz', State_Region__c='California', Postal_Code__c='95062');
       insert site;
       List<Sites__c> sites = [select id from Sites__c where id=:site.Id];
       Test.setMock(HttpCalloutMock.class, new MainspringCiceroMockImpl(jsonError));
       test.startTest();
            MainspringCiceroQueueable msq = new MainspringCiceroQueueable(sites, sites.size(), 0);
            System.enqueueJob(msq);
       test.stopTest();
       System.assertEquals(1, msq.numberOfSites);
    }

    @istest
    private static void testMainspringCiceroSchedulable() {
       Test.setMock(HttpCalloutMock.class, new MainspringCiceroMockImpl(jsonError));
       test.startTest();
            String cronExp ='0 48 * * * ?';
            String jobId = System.schedule('JobName', cronExp, new MainspringCiceroSchedulable());
       test.stopTest();     
       CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
       System.assertNotEquals(null, String.valueOf(ct.NextFireTime));   
    }
}