force-app/main/default/objects/Scorecard_Snapshot__c/Scorecard_Snapshot__c.object-meta.xml
<CustomObject>
    <description>2025-August - These are created automatically to capture Scorecard Scores at the beginning of each month.</description>
    <label>Scorecard Snapshot</label>
    <nameField>
        <displayFormat>SCSS-{0000000}</displayFormat>
        <label>Scorecard Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scorecard_Snapshot__c/fields/Delta__c.field-meta.xml
<CustomField>
    <fullName>Delta__c</fullName>
    <label>Delta</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scorecard_Snapshot__c/fields/Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Name__c</fullName>
    <label>Owner Name</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scorecard_Snapshot__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>AUTO - The parent record Id, either an Account (001) or Opportunity (006).</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scorecard_Snapshot__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scorecard_Snapshot__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scorecard_Snapshot__c/fields/Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Stage_Name__c</fullName>
    <label>Stage Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScorecardSnapshotBatch.cls
public class ScorecardSnapshotBatch implements Database.Batchable<sObject> {

    private String 					table;
    private List<sObject> 			recs;
    private Map<String, Decimal> 	oldScores;
    private Map<String, String>     ownerIdtoName;
    
    public ScorecardSnapshotBatch(String t) {
        table = t;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String q  = 'SELECT Id, Name, Scorecard_Score__c, OwnerId';
               q += table == 'Opportunity' ? ', StageName, CloseDate, Probability' : '';
               q += (' FROM ' + table + ' WHERE Scorecard_Score__c != null');
        return Database.getQueryLocator(q);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
    	recs = scope;
        getOldScores();
        getOwnerMap();
        List<Scorecard_Snapshot__c> newEntries = new List<Scorecard_Snapshot__c>();
        for (sObject o : recs) {
            newEntries.add(getNewRecord(o));
        }
        INSERT newEntries;
    }
    
    public void finish(Database.BatchableContext bc) {
        if (table == 'Account' && !Test.isRunningTest()) {
            Database.executeBatch(new ScorecardSnapshotBatch('Opportunity'));
        }
    }
    
    private void getOldScores() {
        oldScores = new Map<String, Decimal>();
        for (sObject o : recs) {
            oldScores.put(o.Id, null);
        }
        for (Scorecard_Snapshot__c s : [SELECT Record_Id__c, 
                                               Score__c 
                                        FROM   Scorecard_Snapshot__c 
                                        WHERE  CreatedDate >= :System.now().addDays(-34)
                                        AND    Record_Id__c IN :oldScores.keySet()]) {
            oldScores.put(s.Record_Id__c, s.Score__c);
        }
    }
    
    private void getOwnerMap() {
        ownerIdtoName = new Map<String, String>();
        for (sObject o : recs) {
            ownerIdToName.put((String)o.get('OwnerId'), null);
        }
        for (User u : [SELECT Id, Name FROM User WHERE Id IN :ownerIdToName.keySet()]) {
            ownerIdToName.put(u.Id, u.Name);
        }
    }
    
    private Scorecard_Snapshot__c getNewRecord(sObject o) {
        String k  = (String)o.get('Id');
        Decimal v = (Decimal)o.get('Scorecard_Score__c');
        
        Scorecard_Snapshot__c r = new Scorecard_Snapshot__c(
            Record_Id__c   = k,
            Record_Name__c = (String)o.get('Name'),
            Record_Type__c = table,
            Date__c		   = System.today(),
            Score__c	   = v,
            Delta__c       = oldScores.get(k) == null ? null : v - oldScores.get(k),
            Owner_Name__c  = ownerIdToName.get((String)o.get('OwnerId'))
        );
        
        if (table == 'Opportunity') {
            r.Stage_Name__c  = (String)o.get('StageName');
            r.Close_Date__c  = (Date)o.get('CloseDate');
            r.Probability__c = (Decimal)o.get('Probability');
        }
        
        return r;
    }
}