force-app/main/default/objects/Scorecard_Snapshot__c/Scorecard_Snapshot__c.object-meta.xml
<CustomObject>
    <description>2025-August - These are created automatically to capture Scorecard Scores at the beginning of each month.</description>
    <label>Scorecard Snapshot</label>
    <nameField>
        <displayFormat>SCSS-{0000000}</displayFormat>
        <label>Scorecard Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scorecard_Snapshot__c/fields/Delta__c.field-meta.xml
<CustomField>
    <fullName>Delta__c</fullName>
    <label>Delta</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scorecard_Snapshot__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>AUTO - The parent record Id, either an Account (001) or Opportunity (006).</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scorecard_Snapshot__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scorecard_Snapshot__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScorecardSnapshotTest.cls
@isTest
private class ScorecardSnapshotTest {

    @TestSetup
    static void setup() {
        Account a = new Account(
        	Name 				= 'test',
            Scorecard_Type__c 	= 'General-BTM'
        );
        INSERT a;
        
        Contact c = new Contact(
        	AccountId 	= a.Id,
            LastName 	= 'test'
        );
        INSERT c;
        
        Opportunity o = new Opportunity(
        	CloseDate 	= System.today().addDays(15),
            Name 		= 'test opp',
            AccountId 	= a.Id,
            StageName 	= 'Initial Assessment'
        );
        INSERT o;
    }
    
    @isTest
    static void acc() {
        Account a = [SELECT Id, Name FROM Account LIMIT 1];
        INSERT new Scorecard_Snapshot__c(
        	Record_Id__c = a.Id,
            Record_Name__c = a.Name,
            Record_Type__c = 'Account',
            Date__c = System.today().addDays(-30),
            Score__c = 20,
            Delta__c = null
        );
        UPDATE new Account(Id = a.Id, Scorecard_Score__c = 40);
        ScorecardSnapshotSched j = new ScorecardSnapshotSched();
        Test.startTest();
        j.execute(null);
        Test.stopTest();
        
        List<Scorecard_Snapshot__c> entries = [SELECT Id FROM Scorecard_Snapshot__c];
        Assert.areEqual(2, entries.size());
    }
    
    @isTest
    static void opp() {
        Opportunity o = [SELECT Id, Name FROM Opportunity LIMIT 1];
        INSERT new Scorecard_Snapshot__c(
        	Record_Id__c = o.Id,
            Record_Name__c = o.Name,
            Record_Type__c = 'Opportunity',
            Date__c = System.today().addDays(-30),
            Score__c = 20,
            Delta__c = null
        );
        UPDATE new Opportunity(Id = o.Id, Scorecard_Score__c = 40);
        Test.startTest();
        Database.executeBatch(new ScorecardSnapshotBatch('Opportunity'));
        Test.stopTest();
        
        List<Scorecard_Snapshot__c> entries = [SELECT Id FROM Scorecard_Snapshot__c];
        Assert.areEqual(2, entries.size());
    }
}