force-app/main/default/objects/Analytics_Model__c/Analytics_Model__c.object-meta.xml
<CustomObject>
    <label>Analytics Model</label>
    <nameField>
        <label>Analytics Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Analytics Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Analytics_Model__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>Info Needed</fullName>
            </value>
            <value>
                <fullName>Ready for Analysis</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>Validation</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Finalize Proposal</fullName>
            </value>
            <value>
                <fullName>Proposal Check</fullName>
            </value>
            <value>
                <fullName>Ready for Dispatch</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Analytics_Model__c/fields/Stage_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Stage_Start_Time__c</fullName>
    <label>Stage_Start_Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Analytics_Model__c/fields/Time_Spent_in_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_in_Analysis__c</fullName>
    <label>Time Spent in Analysis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Analytics_Model__c/fields/Time_Spent_in_Info_Needed__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_in_Info_Needed__c</fullName>
    <label>Time Spent in Info Needed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Analytics_Model__c/fields/Time_Spent_in_Ready_for_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_in_Ready_for_Analysis__c</fullName>
    <label>Time Spent in Ready for Analysis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Analytics_Model__c/fields/Time_Spent_in_Ready_for_Review__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_in_Ready_for_Review__c</fullName>
    <label>Time Spent in Ready for Review</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Analytics_Model__c/fields/Time_Spent_in_To_Do__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_in_To_Do__c</fullName>
    <label>Time Spent in To Do</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Analytics_Model__c/fields/Time_Spent_in_Validation__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_in_Validation__c</fullName>
    <label>Time Spent in Validation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateCurrentStageDurationBatch.cls
global class UpdateCurrentStageDurationBatch implements Database.Batchable<SObject>, Database.Stateful {

    // Define the query to get records that need stage duration updates
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(
            'SELECT Id, Stage__c,Time_Spent_in_To_Do__c, Stage_Start_Time__c, Time_Spent_in_Info_Needed__c, Time_Spent_in_Ready_for_Review__c, ' +
            'Time_Spent_in_Ready_for_Analysis__c, Time_Spent_in_Analysis__c, Time_Spent_in_Validation__c ' +
            'FROM Analytics_Model__c ' +
            'WHERE Stage__c = \'To Do\' OR Stage__c = \'Info Needed\' OR Stage__c = \'Ready for Analysis\' OR Stage__c = \'Analysis\' OR Stage__c = \'Validation\' ' +
            'ORDER BY CreatedDate DESC'
        );
    }

    // Process each batch of records
    global void execute(Database.BatchableContext BC, List<Analytics_Model__c> records) {
        // Get the Business Hours ID (replace with your business hours ID)
        Id businessHoursId = [SELECT Id FROM BusinessHours WHERE IsDefault = true LIMIT 1].Id;

        List<Analytics_Model__c> recordsToUpdate = new List<Analytics_Model__c>();

        // Loop through each record to update the current stage duration
        for (Analytics_Model__c record : records) {
            // Calculate the current duration in the current stage
                DateTime now = DateTime.now();
                DateTime stageStartTime ;
                if(record.Stage__c == 'To Do'){
                    stageStartTime = record.Stage_Start_Time__c;
                    if(stageStartTime != null){
                    Long timeSpentInCurrentStage = BusinessHours.diff(businessHoursId, stageStartTime, now)/1000; // Time calculated in seconds
                    timeSpentInCurrentStage = timeSpentInCurrentStage/60; // Time calculated in minutes
                    record.Time_Spent_in_To_Do__c = timeSpentInCurrentStage/60;
                    recordsToUpdate.add(record);
                    }
                }
                else if(record.Stage__c == 'Info Needed'){
                    stageStartTime = record.Stage_Start_Time__c;
                    if(stageStartTime != null){
                    Long timeSpentInCurrentStage = BusinessHours.diff(businessHoursId, stageStartTime, now)/1000; // Time calculated in seconds
                    timeSpentInCurrentStage = timeSpentInCurrentStage/60; // Time calculated in minutes
                    record.Time_Spent_in_Info_Needed__c = timeSpentInCurrentStage/60;                   
                    recordsToUpdate.add(record);
                    }
                }
                else if(record.Stage__c == 'Ready for Analysis'){
                    stageStartTime = record.Stage_Start_Time__c;
                    if(stageStartTime != null){
                    Long timeSpentInCurrentStage = BusinessHours.diff(businessHoursId, stageStartTime, now)/1000; // Time calculated in seconds
                    timeSpentInCurrentStage = timeSpentInCurrentStage/60; // Time calculated in minutes
                    record.Time_Spent_in_Ready_for_Analysis__c = timeSpentInCurrentStage/60;                   
                    recordsToUpdate.add(record);
                    }
                }
                else if(record.Stage__c == 'Analysis'){
                    stageStartTime = record.Stage_Start_Time__c;
                    if(stageStartTime != null){
                    Long timeSpentInCurrentStage = BusinessHours.diff(businessHoursId, stageStartTime, now)/1000; // Time calculated in seconds
                    timeSpentInCurrentStage = timeSpentInCurrentStage/60; // Time calculated in minutes
                    record.Time_Spent_in_Analysis__c = timeSpentInCurrentStage/60;                   
                    recordsToUpdate.add(record);
                    }
                }
                 else if(record.Stage__c == 'Validation'){
                    stageStartTime = record.Stage_Start_Time__c;
                    if(stageStartTime != null){
                    Long timeSpentInCurrentStage = BusinessHours.diff(businessHoursId, stageStartTime, now)/1000; // Time calculated in seconds
                    timeSpentInCurrentStage = timeSpentInCurrentStage/60; // Time calculated in minutes
                    record.Time_Spent_in_Validation__c = timeSpentInCurrentStage/60;
                    recordsToUpdate.add(record);
                    }
                }

            }
             // Update the records with the new duration values
        if (!recordsToUpdate.isEmpty()) {
        system.debug('list size:' +recordsToUpdate.size());
            update recordsToUpdate;
        }

    }

    // Finish method
    global void finish(Database.BatchableContext BC) {
        // Optional: Send email notifications or logs when the batch finishes
    }
}