force-app/main/default/objects/Scorecard_Stage_History__c/Scorecard_Stage_History__c.object-meta.xml
<CustomObject>
    <description>2025-August - These records are created automatically by Apex when Opportunity Stage is changed.</description>
    <label>Scorecard Stage History</label>
    <nameField>
        <displayFormat>SSH-{000000}</displayFormat>
        <label>Scorecard Stage History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Stage History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scorecard_Stage_History__c/fields/Account_Score__c.field-meta.xml
<CustomField>
    <fullName>Account_Score__c</fullName>
    <label>Account Score</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scorecard_Stage_History__c/fields/New_Stage__c.field-meta.xml
<CustomField>
    <fullName>New_Stage__c</fullName>
    <label>New Stage</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scorecard_Stage_History__c/fields/Old_Stage__c.field-meta.xml
<CustomField>
    <fullName>Old_Stage__c</fullName>
    <label>Old Stage</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scorecard_Stage_History__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scorecard Stage History</relationshipLabel>
    <relationshipName>Scorecard_Stage_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scorecard_Stage_History__c/fields/Opportunity_Score__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Score__c</fullName>
    <label>Opportunity Score</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scorecard_Stage_History__c/fields/Scorecard_Type__c.field-meta.xml
<CustomField>
    <fullName>Scorecard_Type__c</fullName>
    <label>Scorecard Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityScorecardStageHistory.cls
public class OpportunityScorecardStageHistory {
    
    private List<ProtoSSH>   newRecs;
    private Map<Id, Account> accMap;
    
    public OpportunityScoreCardStageHistory() {
        newRecs = new List<ProtoSSH>();
    }
    
    public void add(String o, String a, String n, String v, Decimal s) {
        newRecs.add(new ProtoSSH(o, a, n, v, s));
    }
    
    public void execute() {        
        if (newRecs.isEmpty()) {
            return;
        }
        getAccMap();
        makeRecs();
    }
    
    private void getAccMap() {
        Set<String> aids = new Set<String>();
        for (ProtoSSH p : newRecs) {
            aids.add(p.aid);
        }
        accMap = new Map<Id, Account>(
        	[SELECT Id,
                    Scorecard_Score__c,
                    Scorecard_Type__c
             FROM   Account
             WHERE  Id IN :aids]
        );
    }
    
    private void makeRecs() {
        List<Scorecard_Stage_History__c> newEntries = new List<Scorecard_Stage_History__c>();
        for (ProtoSSH p : newRecs) {
            Account a = accMap.get(p.aid);
            if (p.score == null && a.Scorecard_Score__c == null) {
                continue;
            }
            newEntries.add(new Scorecard_Stage_History__c(
            	Opportunity__c 			= p.oid,
                New_Stage__c   			= p.newStage,
                Old_Stage__c   			= p.oldStage,
                Date__c		   			= System.today(),
                Account_Score__c 		= a.Scorecard_Score__c,
                Scorecard_Type__c 		= a.Scorecard_Type__c,
                Opportunity_Score__c 	= p.score
            ));
        }
        INSERT newEntries;
    }
    
    private class ProtoSSH {
        private String  oid;
        private String  aid;
        private String  newStage;
        private String  oldStage;
        private Decimal score;
        
        public ProtoSSH(String o, String a, String n, String v, Decimal s) {
            oid 		= o;
            aid			= a;
            newStage 	= n;
            oldStage	= v;
            score		= s;
        }
    }
}