force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/MS_FSM_Asset_Transaction_Log__c.object-meta.xml
<CustomObject>
    <description>Purpose of this Asset is to capture key Asset Details, upon transactions like Location Change, Install, and Remove for Reporting Purposes</description>
    <label>Asset Transaction Log</label>
    <nameField>
        <displayFormat>AT-{00000000}</displayFormat>
        <label>Asset Transaction Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Asset_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Asset_Id__c</fullName>
    <description>Purpose of this field is to capture the Id value of the Asset</description>
    <externalId>true</externalId>
    <label>Asset Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Asset_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Asset_Serial_Number__c</fullName>
    <description>Purpose of this field is to capture the asset&apos;s serial number of the transaction</description>
    <label>Asset Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Status__c</fullName>
    <description>Status of the Asset after the transaction is logged</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Timestamp__c</fullName>
    <description>Timestamp of the transaction related to the asset.</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/MS_FSM_EtaHub_Asset_Staging__c.object-meta.xml
<CustomObject>
    <description>INTEGRATION ONLY - This table holds Ids from EtaHub to be processed into the Asset and Asset Transaction Log table.</description>
    <label>EtaHub Asset Staging</label>
    <nameField>
        <displayFormat>EAS-{0000}</displayFormat>
        <label>EtaHub Asset Transaction Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EtaHub Asset Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Asset_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Asset_Id__c</fullName>
    <description>Salesforce Asset Id provided by EtaHub</description>
    <label>Asset Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Asset_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Asset_Serial_Number__c</fullName>
    <description>Serial Number of the asset transacting on.</description>
    <label>Asset Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Description__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Description__c</fullName>
    <description>stores the product description from an EtaHub Staging Record</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Parent_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Parent_Serial_Number__c</fullName>
    <description>Serial Number of the Parent Asset</description>
    <label>Parent Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Part_Number__c</fullName>
    <description>Used for Product2 mapping</description>
    <label>Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Status__c</fullName>
    <description>Either installed or obsolete status for the asset</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Timestamp__c</fullName>
    <description>Time of the status change.</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/MS_FSM_AssetStagingTest.cls
@isTest
private class MS_FSM_AssetStagingTest {
    
    @isTest
    static void newAsset() {
        List<Product2> prods = new List<Product2>();
        Product2 pa = new Product2(
        	Name 		= 'test product',
            ProductCode = 'ABC'
        );
        Product2 pb = new Product2(
        	Name 		= 'test other',
            ProductCode = 'DEF'
        );
        prods.add(pa);
        prods.add(pb);
        INSERT prods;
        
        AssetTriggerHandler.skipProcessing();
        INSERT new Asset(
            Name 		 = 'test parent',
        	Product2Id 	 = pa.Id,
            SerialNumber = '123'
        );
        
        Test.startTest();
        INSERT new MS_FSM_EtaHub_Asset_Staging__c(
        	MS_FSM_Status__c 				= 'Installed',
            MS_FSM_Asset_Serial_Number__c 	= '456',
            MS_FSM_Part_Number__c 			= 'DEF',
            MS_FSM_Description__c 			= 'test staging asset',
            MS_FSM_Timestamp__c 			= System.now().addMinutes(-10),
            MS_FSM_Parent_Serial_Number__c 	= '123'
        );
        Test.stopTest();
    }
    
    @isTest
    static void existingAsset() {
        List<Product2> prods = new List<Product2>();
        Product2 pa = new Product2(
        	Name 		= 'test product',
            ProductCode = 'ABC'
        );
        Product2 pb = new Product2(
        	Name 		= 'test other',
            ProductCode = 'DEF'
        );
        prods.add(pa);
        prods.add(pb);
        INSERT prods;
        
        AssetTriggerHandler.skipProcessing();
        Asset t = new Asset(
            Name 		 = 'test update',
        	Product2Id 	 = pa.Id,
            SerialNumber = '123'
        );
        INSERT t;
        
        Test.startTest();
        INSERT new MS_FSM_EtaHub_Asset_Staging__c(
            MS_FSM_Asset_Id__c				= t.Id,
        	MS_FSM_Status__c 				= 'Installed',
            MS_FSM_Asset_Serial_Number__c 	= '123',
            MS_FSM_Part_Number__c 			= 'ABC',
            MS_FSM_Description__c 			= 'test staging asset',
            MS_FSM_Timestamp__c 			= System.now().addMinutes(-10)
        );
        Test.stopTest();
    }
    
    @isTest
    static void existingAtl() {
        List<Product2> prods = new List<Product2>();
        Product2 pa = new Product2(
        	Name 		= 'test product',
            ProductCode = 'ABC'
        );
        Product2 pb = new Product2(
        	Name 		= 'test other',
            ProductCode = 'DEF'
        );
        prods.add(pa);
        prods.add(pb);
        INSERT prods;
        
        AssetTriggerHandler.skipProcessing();
        Asset t = new Asset(
            Name 		 = 'test update',
        	Product2Id 	 = pa.Id,
            SerialNumber = '123'
        );
        INSERT t;
        INSERT new MS_FSM_Asset_Transaction_Log__c(
        	MS_FSM_Asset_Id__c 	= t.Id,
            MS_FSM_Timestamp__c = System.now().addHours(-1)
        );
        
        Test.startTest();
        INSERT new MS_FSM_EtaHub_Asset_Staging__c(
            MS_FSM_Asset_Id__c				= t.Id,
        	MS_FSM_Status__c 				= 'Installed',
            MS_FSM_Asset_Serial_Number__c 	= '123',
            MS_FSM_Part_Number__c 			= 'ABC',
            MS_FSM_Description__c 			= 'test staging asset',
            MS_FSM_Timestamp__c 			= System.now().addHours(-2)
        );
        Test.stopTest();
    }
}