force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/MS_FSM_Asset_Transaction_Log__c.object-meta.xml
<CustomObject>
    <description>Purpose of this Asset is to capture key Asset Details, upon transactions like Location Change, Install, and Remove for Reporting Purposes</description>
    <label>Asset Transaction Log</label>
    <nameField>
        <displayFormat>AT-{00000000}</displayFormat>
        <label>Asset Transaction Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Asset_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Asset_Id__c</fullName>
    <description>Purpose of this field is to capture the Id value of the Asset</description>
    <externalId>true</externalId>
    <label>Asset Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Asset_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Asset_Serial_Number__c</fullName>
    <description>Purpose of this field is to capture the asset&apos;s serial number of the transaction</description>
    <label>Asset Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_EtaHub_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_EtaHub_Record_Id__c</fullName>
    <description>Purpose of this field is to capture the EtaHub record Id</description>
    <label>EtaHub Record Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_EtaHub_Source_Table__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_EtaHub_Source_Table__c</fullName>
    <label>EtaHub Source Table</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Method_of_Creation__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Method_of_Creation__c</fullName>
    <label>Method of Creation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EtaHub Asset Staging</fullName>
            </value>
            <value>
                <fullName>Obsolete Asset Flow</fullName>
            </value>
            <value>
                <fullName>Upgrades</fullName>
            </value>
            <value>
                <fullName>Rebuild Asset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Parent_Asset_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Parent_Asset_Serial_Number__c</fullName>
    <description>Purpose of this field is to capture the parent asset&apos;s serial number</description>
    <label>Parent Asset Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Root_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Root_Serial_Number__c</fullName>
    <description>Purpose of this field is to track the root asset serial number at the time of creation of the log.</description>
    <label>Root Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Run_Hours__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Run_Hours__c</fullName>
    <description>Purpose of this Field is to capture relevant Asset Run Hours at the time of Install or Removal</description>
    <label>Run Hours</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Status__c</fullName>
    <description>Status of the Asset after the transaction is logged</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Timestamp__c</fullName>
    <description>Timestamp of the transaction related to the asset.</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Transaction_Type__c</fullName>
    <description>Purpose of this field is to capture the type of asset transaction made</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Status Change</fullName>
            </value>
            <value>
                <fullName>Location Change</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/MS_FSM_EtaHub_Asset_Staging__c.object-meta.xml
<CustomObject>
    <description>INTEGRATION ONLY - This table holds Ids from EtaHub to be processed into the Asset and Asset Transaction Log table.</description>
    <label>EtaHub Asset Staging</label>
    <nameField>
        <displayFormat>EAS-{0000}</displayFormat>
        <label>EtaHub Asset Transaction Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EtaHub Asset Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Asset_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Asset_Id__c</fullName>
    <description>Salesforce Asset Id provided by EtaHub</description>
    <label>Asset Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Asset_Placement__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Asset_Placement__c</fullName>
    <description>INT or EXH</description>
    <label>Asset Placement</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Asset_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Asset_Serial_Number__c</fullName>
    <description>Serial Number of the asset transacting on.</description>
    <label>Asset Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Description__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Description__c</fullName>
    <description>stores the product description from an EtaHub Staging Record</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_EtaHub_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_EtaHub_Record_Id__c</fullName>
    <description>Record Id of the EtaHub transaction.</description>
    <label>EtaHub Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_EtaHub_Table_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_EtaHub_Table_Id__c</fullName>
    <description>Table Id of the EtaHub transaction</description>
    <label>EtaHub Table Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Method_of_Creation__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Method_of_Creation__c</fullName>
    <description>Used to define which process created the EtaHub Asset Staging record. Upgrades workspace is in EtaHub. Rebuild Asset is fired off a button the Asset in FSM and triggers an update in EtaHub to create staging records</description>
    <label>Method of Creation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upgrades</fullName>
            </value>
            <value>
                <fullName>Rebuild Asset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Parent_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Parent_Serial_Number__c</fullName>
    <description>Serial Number of the Parent Asset</description>
    <label>Parent Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Part_Number__c</fullName>
    <description>Used for Product2 mapping</description>
    <label>Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Quantity__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Quantity__c</fullName>
    <description>Quantity for batched assets</description>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Removal_Disposition__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Removal_Disposition__c</fullName>
    <description>Disposition when the asset is removed.</description>
    <label>Removal Disposition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Root_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Root_Serial_Number__c</fullName>
    <description>stores the root serial number of a product from an Etahub Staging record</description>
    <label>Root Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Stage__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Stage__c</fullName>
    <description>Used within the Asset Trigger helper to define the stage of the integration processing done in MS_FSM_EHINT_AssetStagingTriggerHelper</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Processed - New Asset</fullName>
            </value>
            <value>
                <fullName>Processed - Later ATL Found - New ATL Only</fullName>
            </value>
            <value>
                <fullName>Processed - New ATL and Asset Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Status__c</fullName>
    <description>Either installed or obsolete status for the asset</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Asset_Staging__c/fields/MS_FSM_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Timestamp__c</fullName>
    <description>Time of the status change.</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/MS_FSM_AssetStagingProcessing.cls
/******************************************************************************
 * Name         : MS_FSM_AssetStagingProcessing
 * Author       : Nathan Ehrmann - nathan@empowherops.com
 * Created Date : 2025-06-01
 * Description  : this enables a Pipeline-driven "upgrades" process by taking in
 * 				  Staging records (MS_FSM_Asset_Staging__c) and processing them into
 * 				  Asset updates and Asset Transaction Log inserts.
 *
 * Modification History:
 *   Date       | Author              | Change Description
 *   -----------|---------------------|------------------------------------------
 *   2025-06-01 | Nathan Ehrmann      | Initial write.
 *
 * Notes:
 * 
 * Tests:
 * MS_FSM_AssetStagingTest
 ******************************************************************************/
public class MS_FSM_AssetStagingProcessing {

    private List<MS_FSM_EtaHub_Asset_Staging__c> recs;
    
    private Map<String, String> 						prodCodeToProdId 			= new Map<String, String>();
    private Map<String, Asset>  						assetIdToAsset   			= new Map<String, Asset>();
    private Map<String, AssetHistory>					assetIdToRunHours			= new Map<String, AssetHistory>();
    private Map<String, MS_FSM_EtaHub_Asset_Staging__c> assetIdToStaging 			= new Map<String, MS_FSM_EtaHub_Asset_Staging__c>();
    private Map<String, String>							assetStagingIdToOutcome		= new Map<String, String>();
    private List<Asset>									newAssets					= new List<Asset>();
    private List<Asset>									updateAssets				= new List<Asset>();
    private List<MS_FSM_EtaHub_Asset_Staging__c>		updateStages				= new List<MS_FSM_EtaHub_Asset_Staging__c>();
    private List<MS_FSM_Asset_Transaction_Log__c> 		newAtl						= new List<MS_FSM_Asset_Transaction_Log__c>();   
    private List<MS_FSM_Asset_Transaction_Log__c> 		exAtl;
    private DateTime 									minimum;
    private DateTime									maximum;
    
    private final String DATA_USER = '005Qr00000B2n4lIAB';
    
    public MS_FSM_AssetStagingProcessing(List<MS_FSM_EtaHub_Asset_Staging__c> r) {
        recs = r;
    }
    
    public void execute() {
        initialize();
        AssetTriggerHandler.skipProcessing();
        createAssets();
        checkAtl();
        processStaging();
        finalize();
        toParenting();
    }
    
    private void initialize() {
        for (MS_FSM_EtaHub_Asset_Staging__c s : recs) {
            if (!String.isBlank(s.MS_FSM_Asset_Id__c)) {
                assetIdToStaging.put(s.MS_FSM_Asset_Id__c, s);
                assetIdToAsset.put(s.MS_FSM_Asset_Id__c, null);
            }
            
            if (!String.isBlank(s.MS_FSM_Part_Number__c)) {
                prodCodeToProdId.put(s.MS_FSM_Part_Number__c, null); 
            }
            
            DateTime t 			= s.MS_FSM_Timestamp__c;
            		 minimum 	= (minimum == null || t < minimum) ? t : minimum;
            		 maximum    = (maximum == null || t > maximum) ? t : maximum;
        }
        buildAssetMap();
        buildProdMap();
        buildRunHoursMap();
        getAtl();
    }
    
    private void finalize() {
        UPDATE updateAssets;
        INSERT newAtl;
        UPDATE updateStages;
    }
    
    private void toParenting() {
        List<String> PARENTING_CLASS_NAMES = new List<String> {
            'MS_FSM_EHINT_AssetStagingParentingSched',
            'MS_FSM_EHINT_AssetStagingParentingQ'
        };
                    
        DateTime 	p = System.now().addMinutes(5);
        String 		c = '' + p.second() + ' ' + p.minute() + ' ' + p.hour() + ' ' + p.day() + ' ' + p.month() + ' ? ' + p.year();
        
        List<AsyncApexJob> jobs = [SELECT 	Id 
                                   FROM 	AsyncApexJob 
                                   WHERE 	ApexClass.Name IN :PARENTING_CLASS_NAMES 
                                   AND 		Status IN ('Holding', 'Preparing', 'Processing', 'Queued')];
        
        if (jobs.isEmpty()) {
            System.schedule('Staging Record Parenting ' + String.valueOf(p), c, new MS_FSM_AssetStagingParentingSched());
        } 
    }
    
    private void updateStage(String sid, String s) {
        updateStages.add(new MS_FSM_EtaHub_Asset_Staging__c(Id = sid, MS_FSM_Stage__c = s));
    }
    
    private void createAssets() {
        List<MS_FSM_EtaHub_Asset_Staging__c> recsWithNewAssets = new List<MS_FSM_EtaHub_Asset_Staging__c>();
        for (MS_FSM_EtaHub_Asset_Staging__c s : recs) {
            if (!String.isBlank(s.MS_FSM_Asset_Id__c)) {
                continue;
            }
            recsWithNewAssets.add(s);
            newAssets.add(mapAsset(s));
        }
        INSERT newAssets;
        for (Integer i = 0; i < newAssets.size(); i++) {
            MS_FSM_EtaHub_Asset_Staging__c 	s = recsWithNewAssets[i];
            Asset 							t = newAssets[i];
            newAtl.add(createAtl(s, t));
            updateStages.add(new MS_FSM_EtaHub_Asset_Staging__c(
            	Id 					= s.Id,
                MS_FSM_Stage__c 	= 'Processed - New Asset',
                MS_FSM_Asset_Id__c 	= t.Id
            ));
        }
    }
    
    private void checkAtl() {
        for (MS_FSM_Asset_Transaction_Log__c atl : exAtl) {
            MS_FSM_EtaHub_Asset_Staging__c stage = assetIdToStaging.get(atl.MS_FSM_Asset_Id__c);
            if (assetStagingIdToOutcome.containsKey(stage.Id)) {										// already processed
                continue;
            }
            if (atl.MS_FSM_Timestamp__c < stage.MS_FSM_Timestamp__c) {
                continue;
            }
            // now, we proceed knowing that the ATL is 
            // LATER THAN the provided upgrade/staging record
            if (isMatch(stage, atl)) {
                assetStagingIdToOutcome.put(stage.Id, 'DUPLICATE');										// this means we will potentially just apply updates to the Asset
            } else {
                assetStagingIdToOutcome.put(stage.Id, 'LATER ATL EXISTS');  							// this means we will create an ATL, but not update the Asset
            }
        }
    }
    
    private void processStaging() {
        for (MS_FSM_EtaHub_Asset_Staging__c s : recs) {
            if (String.isBlank(s.MS_FSM_Asset_Id__c)) {			// ALREADY PROCESSED by creating new Asset + ATL
                continue;
            }
            
            Asset a = assetIdToAsset.get(s.MS_FSM_Asset_Id__c);
            
            switch on (assetStagingIdToOutcome.containsKey(s.Id) ? assetStagingIdToOutcome.get(s.Id) : 'NO LATER ATL') {
                when 'NO LATER ATL' {
                    updateStage(s.Id, 'Processed - New ATL and Asset Update');
                    updateAssets.add(mapAsset(s));
                    newAtl.add(createAtl(s, a));
                }
                when 'DUPLICATE' {
                    updateStage(s.Id, 'Not Applicable');
                } 
                when 'LATER ATL EXISTS' {
                    updateStage(s.Id, 'Processed - Later ATL Found - New ATL Only');
                    newAtl.add(createAtl(s, a));
                }
            }
        }
    }
    
    private Boolean isMatch(MS_FSM_EtaHub_Asset_Staging__c s, MS_FSM_Asset_Transaction_Log__c atl) {
        return s.MS_FSM_Timestamp__c            == atl.MS_FSM_Timestamp__c &&
               s.MS_FSM_Status__c               == atl.MS_FSM_Status__c    &&
               s.MS_FSM_Parent_Serial_Number__c == atl.MS_FSM_Parent_Asset_Serial_Number__c;
    }
    
    private Asset mapAsset(MS_FSM_EtaHub_Asset_Staging__c s) {
        String 	status 		= s.MS_FSM_Status__c;
        Boolean isInstall 	= status == 'Installed';
        Asset a = new Asset(
            Status 							= status,
            MS_FSM_EtaHub_Table_Id__c 		= s.MS_FSM_EtaHub_Table_Id__c,
            MS_FSM_EtaHub_Record_Id__c 		= s.MS_FSM_EtaHub_Record_Id__c,
            Description 					= s.MS_FSM_Description__c,
            Name 							= s.MS_FSM_Asset_Serial_Number__c + ' | ' + s.MS_FSM_Part_Number__c + ' - ' + s.MS_FSM_Description__c,
            SerialNumber				 	= s.MS_FSM_Asset_Serial_Number__c,
            MS_FSM_Usage_End_Date_Time__c 	= isInstall ? null : s.MS_FSM_Timestamp__c
        );
        if (!String.isBlank(s.MS_FSM_Asset_Id__c)) {
            a.Id = s.MS_FSM_Asset_Id__c;
        } else {
            a.Product2Id  					= prodCodeToProdId.get(s.MS_FSM_Part_Number__c);
            a.Quantity 	  					= s.MS_FSM_Quantity__c;
            a.MS_FSM_Method_of_Creation__c 	= 'Upgrades';
        }
        if (isInstall) {
            a.MS_FSM_Install_Date_Time__c 		= s.MS_FSM_Timestamp__c;
            a.MS_FSM_Parent_Serial_Number__c 	= s.MS_FSM_Parent_Serial_Number__c;
            a.MS_FSM_Asset_Placement__c			= s.MS_FSM_Asset_Placement__c;
        } else {
            a.ParentId 							= null;
            a.MS_FSM_Removal_Disposition__c 	= s.MS_FSM_Removal_Disposition__c;
        }
        return a;
    }
    
    private MS_FSM_Asset_Transaction_Log__c createAtl(MS_FSM_EtaHub_Asset_Staging__c s, Asset a) {
        
        return new MS_FSM_Asset_Transaction_Log__c(
        	MS_FSM_Asset_Id__c 					 = a == null ? s.MS_FSM_Asset_Id__c : a.Id,
            MS_FSM_EtaHub_Record_Id__c           = s.MS_FSM_EtaHub_Record_Id__c,
            MS_FSM_Status__c                     = s.MS_FSM_Status__c,
            MS_FSM_Asset_Serial_Number__c        = s.MS_FSM_Asset_Serial_Number__c,
            MS_FSM_Parent_Asset_Serial_Number__c = s.MS_FSM_Parent_Serial_Number__c,
            MS_FSM_EtaHub_Source_Table__c        = s.MS_FSM_EtaHub_Table_Id__c,
            MS_FSM_Transaction_Type__c           = 'Status Change',
            MS_FSM_Method_of_Creation__c 		 = s.MS_FSM_Method_of_Creation__c,
            MS_FSM_Timestamp__c                  = s.MS_FSM_Timestamp__c,
            MS_FSM_Run_Hours__c                  = a == null || !assetIdToRunHours.containsKey(a.Id) ? null : (Decimal)assetIdToRunHours.get(a.Id).NewValue,
            MS_FSM_Root_Serial_Number__c         = s.MS_FSM_Root_Serial_Number__c
        );
    }
    
    private void buildRunHoursMap() {
        for (AssetHistory h : [SELECT CreatedDate, NewValue, AssetId 
                               FROM   AssetHistory
                               WHERE  AssetId      IN :assetIdToAsset.keySet()
                               AND    CreatedDate   < :maximum
                               AND    Field 		= 'MS_FSM_Run_Hours__c'
                               AND    CreatedById 	= :DATA_USER]) 
        {
            MS_FSM_EtaHub_Asset_Staging__c s = assetIdToStaging.get(h.AssetId);
            if (s == null || s.MS_FSM_Timestamp__c < h.CreatedDate) {
                continue;
            }
            AssetHistory r = assetIdToRunHours.get(h.AssetId);
            if (r == null || h.CreatedDate > r.CreatedDate) {
                assetIdToRunHours.put(h.AssetId, h);
            }
        }
    }
    
    private void buildAssetMap() {
        for (Asset a : [SELECT Id, MS_FSM_Run_Hours__c FROM Asset WHERE Id IN :assetIdToAsset.keySet()]) {
            assetIdToAsset.put(a.Id, a);
        }
    }
    
    private void buildProdMap() {
        for (Product2 p : [SELECT Id, ProductCode FROM Product2 WHERE ProductCode IN :prodCodeToProdId.keySet()]) {
            prodCodeToProdId.put(p.ProductCode, p.Id);
        }
    }                                                                                                                                           
    
    private void getAtl() {
        exAtl = [SELECT MS_FSM_Status__c,
            		     MS_FSM_Timestamp__c,
            			 MS_FSM_Parent_Asset_Serial_Number__c,
            			 MS_FSM_Asset_Id__c
            	  FROM   MS_FSM_Asset_Transaction_Log__c
            	  WHERE  MS_FSM_Asset_Id__c IN :assetIdToAsset.keySet()
            	  AND 	MS_FSM_Timestamp__c >= :minimum];
    }
}