force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/MS_FSM_Asset_Transaction_Log__c.object-meta.xml
<CustomObject>
    <description>Purpose of this Asset is to capture key Asset Details, upon transactions like Location Change, Install, and Remove for Reporting Purposes</description>
    <label>Asset Transaction Log</label>
    <nameField>
        <displayFormat>AT-{00000000}</displayFormat>
        <label>Asset Transaction Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Asset_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Asset_Id__c</fullName>
    <description>Purpose of this field is to capture the Id value of the Asset</description>
    <externalId>true</externalId>
    <label>Asset Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Asset_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Asset_Serial_Number__c</fullName>
    <description>Purpose of this field is to capture the asset&apos;s serial number of the transaction</description>
    <label>Asset Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_EtaHub_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_EtaHub_Record_Id__c</fullName>
    <description>Purpose of this field is to capture the EtaHub record Id</description>
    <label>EtaHub Record Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_EtaHub_Source_Table__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_EtaHub_Source_Table__c</fullName>
    <label>EtaHub Source Table</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Location_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Location_Id__c</fullName>
    <description>Purpose of this field is to capture the location Id of an asset transaction</description>
    <label>Location Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Parent_Asset_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Parent_Asset_Serial_Number__c</fullName>
    <description>Purpose of this field is to capture the parent asset&apos;s serial number</description>
    <label>Parent Asset Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Status__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Status__c</fullName>
    <description>Status of the Asset after the transaction is logged</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Timestamp__c</fullName>
    <description>Timestamp of the transaction related to the asset.</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MS_FSM_Asset_Transaction_Log__c/fields/MS_FSM_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Transaction_Type__c</fullName>
    <description>Purpose of this field is to capture the type of asset transaction made</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Status Change</fullName>
            </value>
            <value>
                <fullName>Location Change</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MS_FSM_EHINT_CreateLogsBatch.cls
/******************************************************************************
 * Name         : MS_FSM_EHINT_CreateLogsBatch
 * Author       : Nathan Ehrmann - nathan@empowherops.com
 * Created Date : 2024-11-01
 * Description  : batch class for creating Asset Transaction Logs. ends the
 * 			      CM/Assembly chain.
 *
 * Modification History:
 *   Date       | Author              | Change Description
 *   -----------|---------------------|------------------------------------------
 *   2024-11-01 | Nathan Ehrmann      | Initial write.
 *
 * Notes:
 * 
 * Tests:
 * MS_FSM_EHINT_Tests
 ******************************************************************************/
public class MS_FSM_EHINT_CreateLogsBatch implements Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id,
                                                SerialNumber,
                                                Parent.SerialNumber,
                                                MS_FSM_EtaHub_Table_Id__c,
                                                MS_FSM_EtaHub_Record_Id__c,
                                                MS_FSM_Install_Date_Time__c,
                                                LocationId,
                                          		RootAssetId,
                                                RootAsset.LocationId
                                         FROM   Asset
                                         WHERE  MS_FSM_Create_ATL__c = true]);
    }
    
    public void execute(Database.BatchableContext bc, List<Asset> scope) {
		List<MS_FSM_Asset_Transaction_Log__c> atls = new List<MS_FSM_Asset_Transaction_Log__c>();
        for (Asset a : scope) {
            a.MS_FSM_Create_ATL__c = false;
            atls.add(new MS_FSM_Asset_Transaction_Log__c(
            	MS_FSM_Asset_Serial_Number__c 			= a.SerialNumber,
                MS_FSM_Asset_Id__c 						= a.Id,
                MS_FSM_Status__c 						= 'Installed',
                MS_FSM_Transaction_Type__c 				= 'Status Change',
                MS_FSM_Parent_Asset_Serial_Number__c 	= a.Parent.SerialNumber,
                MS_FSM_EtaHub_Source_Table__c 			= a.MS_FSM_EtaHub_Table_Id__c,
                MS_FSM_EtaHub_Record_Id__c 				= a.MS_FSM_EtaHub_Record_Id__c,
                MS_FSM_Timestamp__c 					= a.MS_FSM_Install_Date_Time__c,
                MS_FSM_Location_Id__c 					= a.RootAsset.LocationId
            ));
        }
        INSERT atls;
        UPDATE scope;
    }
    
    public void finish(Database.BatchableContext bc) { /* DO NOTHING */ }
}