force-app/main/default/objects/Scorecard_Answer__c/Scorecard_Answer__c.object-meta.xml
<CustomObject>
    <label>Scorecard Answer</label>
    <nameField>
        <displayFormat>SCA-{000000}</displayFormat>
        <label>Scorecard Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scorecard_Answer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scorecard Answers</relationshipLabel>
    <relationshipName>Scorecard_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scorecard_Answer__c/fields/Answer_PL__c.field-meta.xml
<CustomField>
    <fullName>Answer_PL__c</fullName>
    <label>Answer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
            </value>
            <value>
                <fullName>False</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard_Answer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scorecard Answers</relationshipLabel>
    <relationshipName>Scorecard_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scorecard_Answer__c/fields/Scorecard_Question__c.field-meta.xml
<CustomField>
    <fullName>Scorecard_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scorecard Question</label>
    <referenceTo>Scorecard_Questions__c</referenceTo>
    <relationshipLabel>Scorecard Answers</relationshipLabel>
    <relationshipName>Scorecard_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scorecard_Questions__c/Scorecard_Questions__c.object-meta.xml
<CustomObject>
    <label>Scorecard Question</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scorecard_Questions__c/fields/Required_For_Stage_Progression__c.field-meta.xml
<CustomField>
    <fullName>Required_For_Stage_Progression__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required For Stage Progression</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scorecard_Questions__c/fields/Restricted_Opportunity_Stages__c.field-meta.xml
<CustomField>
    <fullName>Restricted_Opportunity_Stages__c</fullName>
    <label>Restricted Opportunity Stages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preliminary Meeting</fullName>
            </value>
            <value>
                <fullName>Proposal/RFP Generation</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Negotiating Contract</fullName>
            </value>
            <value>
                <fullName>Final Site Development</fullName>
            </value>
            <value>
                <fullName>Initial Assessment</fullName>
            </value>
            <value>
                <fullName>Indicative Proposal</fullName>
            </value>
            <value>
                <fullName>Firm Proposal</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityScorecardStageGate.cls
public class OpportunityScorecardStageGate {

    private List<Opportunity> newOpps = new List<Opportunity>();
    
    public void add(Opportunity o) {
        newOpps.add(o);
    }
    
    public void execute() {
        if (newOpps.isEmpty()) {
            return;
        }
        check(buildRestrictedSet());
    }
    
    private Set<String> buildRestrictedSet() {
        Set<String> r = new Set<String>();
        for (Scorecard_Answer__c a : [SELECT Id,
                                                Opportunity__c,
                                                Account__c,
                                                Answer_PL__c,
                                                Scorecard_Question__c,
                                         		Scorecard_Question__r.Title__c,
                                                Scorecard_Question__r.Restricted_Opportunity_Stages__c
                                         FROM   Scorecard_Answer__c
                                         WHERE  Scorecard_Question__r.Required_for_Stage_Progression__c = true
                                         AND    Opportunity__c IN :newOpps]) 
        {
            if (a.Answer_PL__c != 'True') {
                for (String s : a.Scorecard_Question__r.Restricted_Opportunity_Stages__c.split(';')) {
                    r.add(a.Opportunity__c + ' ' + s.trim());
                }
            }
        }
        return r;
    }
    
    private void check(Set<String> restrictions) {
        for (Opportunity o : newOpps) {
            if (restrictions.contains(String.valueOf(o.Id) + ' ' + o.StageName)) {
                o.addError('One or more Scorecard Answers of False / Unknown / blank is blocking this stage change. Please review and update the Opportunity Scorecard and reattempt.');
            }
        }
    }
    
}