force-app/main/default/objects/MS_FSM_EtaHub_Integration_Definition__c/MS_FSM_EtaHub_Integration_Definition__c.object-meta.xml
<CustomObject>
    <label>EtaHub Integration Definition</label>
    <nameField>
        <label>EtaHub Integration Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EtaHub Integration Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MS_FSM_EtaHub_Integration_Definition__c/fields/MS_FSM_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>decimal</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>datetime</fullName>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Integration_Definition__c/fields/MS_FSM_EH_Column_Number__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_EH_Column_Number__c</fullName>
    <label>EH Column Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Integration_Definition__c/fields/MS_FSM_EH_Table_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_EH_Table_Id__c</fullName>
    <label>EH Table Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MS_FSM_EtaHub_Integration_Definition__c/fields/MS_FSM_Target_Field__c.field-meta.xml
<CustomField>
    <fullName>MS_FSM_Target_Field__c</fullName>
    <label>Target Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateLgenController.cls
public class CreateLgenController {
    
    @AuraEnabled(cacheable=false)
    public static Map<String, Object> checkSerial(String spid) {
        Map<String, Object> r = new Map<String, Object>();
        String sn = [SELECT SerialNumber FROM SerializedProduct WHERE Id = :spid].SerialNumber;
        
        Boolean found 	= false;
        String 	f 		= '{12.EX.' + sn + '}';
        String  table   = '';
        
        for (MS_FSM_EtaHub_Integration_Definition__c d : [SELECT MS_FSM_EH_Column_Number__c,
                                                          		 MS_FSM_Target_Field__c,
                                                          		 MS_FSM_Data_Type__c,
                                                          		 MS_FSM_EH_Table_Id__c
                                                          FROM 	 MS_FSM_EtaHub_Integration_Definition__c
                                                          WHERE  MS_FSM_EH_Column_Number__c = '12'
                                                          AND    (MS_FSM_EH_Table_Id__c = 'brv5unzwf' OR  MS_FSM_EH_Table_Id__c = 'bnnfe2qf9')]) 
        {
            if (!found) {
                found = !MS_FSM_EHINT_Utils.getEHData(new List<MS_FSM_EtaHub_Integration_Definition__c>{d}, f, 0, 0).isEmpty();
                table = found ? d.MS_FSM_EH_Table_Id__c : '';
            }
        }
        r.put('serial', sn);
		r.put('found',  found);
        r.put('table',  table);
        return r;
    }
    
    @AuraEnabled(cacheable=false)
    public static String buildLgen(String spid, String sn, String tid) {
        try {
            UPDATE new SerializedProduct(Id = spid, LGen_Requested__c = true, LGen_Requester_Email__c = UserInfo.getUserEmail());
            
            String f = '{12.EX.' + sn + '}';
            
            if (tid == 'bnnfe2qf9') {
                MS_FSM_EHINT_GetAssemblies j = new MS_FSM_EHINT_GetAssemblies();
                j.filterOverride = f;
                System.enqueueJob(j);
            }
            if (tid == 'brv5unzwf') {
                MS_FSM_EHINT_GetCMAssemblies j = new MS_FSM_EHINT_GetCMAssemblies();
                j.filterOverride = f;
                System.enqueueJob(j);
            }
        } catch (Exception ex) {
            return ex.getMessage();
        }
        return 'SUCCESS';
    }
}