force-app/main/default/objects/Customer_Dashboard_Permission__c/Customer_Dashboard_Permission__c.object-meta.xml
<CustomObject>
    <label>Customer Dashboard Permission</label>
    <nameField>
        <label>Customer Dashboard Permission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Dashboard Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Dashboard_Permission__c/fields/Customer_Dashboard_Setting__c.field-meta.xml
<CustomField>
    <fullName>Customer_Dashboard_Setting__c</fullName>
    <label>Customer Dashboard Setting</label>
    <referenceTo>Customer_Dashboard_Setting__c</referenceTo>
    <relationshipLabel>Customer Dashboard Permissions</relationshipLabel>
    <relationshipName>Customer_Dashboard_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Dashboard_Permission__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Dashboard_Permission__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Dashboard_Setting__c/Customer_Dashboard_Setting__c.object-meta.xml
<CustomObject>
    <label>Customer Dashboard Setting</label>
    <nameField>
        <label>Customer Dashboard Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Dashboard Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Dashboard_Setting__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomerDbTocController.cls
public without sharing class CustomerDbTocController {

    @AuraEnabled(cacheable=true)
    public static List<Customer_Dashboard_Setting__c> getSettings() {
        User u = getUser();
        if (u == null) {
            return new List<Customer_Dashboard_Setting__c>();
        }
        return [SELECT 	Id, 
                		Name
                FROM   	Customer_Dashboard_Setting__c
                WHERE  	Public__c = true
                OR     	Id IN :getPermedDbs(u)];
    }
    
    private static User getUser() {
        return [SELECT ProfileId, Contact.AccountId FROM User WHERE Id = :UserInfo.getUserId()];
    }
    
    private static Set<String> getPermedDbs(User u) {
        Set<String> dbsids = new Set<String>();
        for (Customer_Dashboard_Permission__c p : [SELECT 	Customer_Dashboard_Setting__c 
                                                   FROM 	Customer_Dashboard_Permission__c
                                                   WHERE 	(Type__c = 'Profile' AND Value__c = :u.ProfileId)
                                                   OR    	(Type__c = 'Account' AND Value__c = :u.Contact.AccountId)]) 
        {
        	dbsids.add(p.Customer_Dashboard_Setting__c);
        }
        return dbsids;
    }
}