force-app/main/default/objects/Scorecard__c/Scorecard__c.object-meta.xml
<CustomObject>
    <label>Scorecard</label>
    <nameField>
        <label>Scorecard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scorecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scorecard__c/fields/Scorecard_Type__c.field-meta.xml
<CustomField>
    <fullName>Scorecard_Type__c</fullName>
    <label>Scorecard Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scorecard_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard_Answer__c/Scorecard_Answer__c.object-meta.xml
<CustomObject>
    <label>Scorecard Answer</label>
    <nameField>
        <displayFormat>SCA-{000000}</displayFormat>
        <label>Scorecard Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scorecard_Answer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scorecard Answers</relationshipLabel>
    <relationshipName>Scorecard_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scorecard_Answer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scorecard Answers</relationshipLabel>
    <relationshipName>Scorecard_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scorecard_Answer__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <formula>TEXT(Scorecard_Question__r.Question_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Question Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scorecard_Questions__c/Scorecard_Questions__c.object-meta.xml
<CustomObject>
    <label>Scorecard Question</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scorecard_Questions__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard_Questions__c/fields/Required_For_Stage_Progression__c.field-meta.xml
<CustomField>
    <fullName>Required_For_Stage_Progression__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required For Stage Progression</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scorecard_Questions__c/fields/Restricted_Opportunity_Stages__c.field-meta.xml
<CustomField>
    <fullName>Restricted_Opportunity_Stages__c</fullName>
    <label>Restricted Opportunity Stages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preliminary Meeting</fullName>
            </value>
            <value>
                <fullName>Proposal/RFP Generation</fullName>
            </value>
            <value>
                <fullName>Term Sheet</fullName>
            </value>
            <value>
                <fullName>Negotiating Contract</fullName>
            </value>
            <value>
                <fullName>Final Site Development</fullName>
            </value>
            <value>
                <fullName>Initial Assessment</fullName>
            </value>
            <value>
                <fullName>Indicative Proposal</fullName>
            </value>
            <value>
                <fullName>Firm Proposal</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scorecard_Questions__c/fields/Scorecard__c.field-meta.xml
<CustomField>
    <fullName>Scorecard__c</fullName>
    <label>Scorecard</label>
    <referenceTo>Scorecard__c</referenceTo>
    <relationshipLabel>Scorecard Questions</relationshipLabel>
    <relationshipName>Scorecard_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scorecard_Questions__c/fields/Scorecard_Type__c.field-meta.xml
<CustomField>
    <fullName>Scorecard_Type__c</fullName>
    <formula>TEXT( Scorecard__r.Scorecard_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scorecard Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityScorecardStageGateTest.cls
@isTest
private class OpportunityScorecardStageGateTest {

    @isTest
    static void standard() {
        Scorecard__c sc = new Scorecard__c(
        	Name   		 		= 'test',
            Scorecard_Type__c  	= 'General-BTM'
        );
        INSERT sc;
        
        List<Scorecard_Questions__c> qs = new List<Scorecard_Questions__c>();
        Scorecard_Questions__c scqa = new Scorecard_Questions__c(
        	Title__c 			= 'test account question',
            Active__c 			= true,
            Scorecard__c 		= sc.Id,
         	Question_Type__c 	= 'Account'   
        );
        qs.add(scqa);
        Scorecard_Questions__c scqb = new Scorecard_Questions__c(
            Title__c 							= 'test opportunity question',
            Active__c 							= true,
            Scorecard__c 						= sc.Id,
            Question_Type__c 					= 'Opportunity',
            Required_For_Stage_Progression__c	= true,
            Restricted_Opportunity_Stages__c    = 'Firm Proposal'
        );
        qs.add(scqb);
        INSERT qs;
        
        Account a = new Account(
        	Name 				= 'test account',
            Scorecard_Type__c 	= 'General-BTM'
        );
        INSERT a;
        
        Opportunity o = new Opportunity(
        	AccountId	= a.Id,
            Name		= 'test opportunity',
            StageName 	= 'Prospecting',
            CloseDate 	= Date.today().addDays(30) 
        );
        INSERT o;
        OpportunityTriggerHandler.reset();
        
        List<Scorecard_Answer__c> scas = [SELECT Id, Account__c, Opportunity__c FROM Scorecard_Answer__c];
        Assert.areEqual(2, scas.size());		// this is actually testing a Flow at this time
        
        Boolean f = false;
        try {
            UPDATE new Opportunity(
            	Id = o.Id,
                StageName = 'Firm Proposal'
            );
        } catch (Exception ex) {
            f = true;
            System.debug('OpportunityScorecardStageGateTest - error updating Opportunity');
            System.debug(ex.getMessage());
        }
        Assert.areEqual(true, f);
    }
    
}